# Generated by Django 5.1.3 on 2024-11-13 19:20

import dream.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dream.models.dream_image_file_path),
        ),
        migrations.AlterField(
            model_name='dream',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='New', max_length=15),
        ),
    ]
