# Generated by Django 5.1.3 on 2025-01-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
