# Generated by Django 5.1.3 on 2025-01-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0003_alter_dream_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
