# Generated by Django 5.1.3 on 2024-11-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0003_dream_accumulated_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='accumulated',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
