# Generated by Django 5.1.3 on 2024-11-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0004_alter_dream_accumulated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='dream',
            options={'ordering': ['-date_added']},
        ),
    ]
