# Generated by Django 5.1.3 on 2024-11-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0005_alter_comment_options_alter_contribution_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dream',
            old_name='likes',
            new_name='views',
        ),
    ]
