# Generated by Django 5.1.3 on 2025-01-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dream', '0005_userfavorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='category',
            field=models.CharField(choices=[('Money_donation', 'Money'), ('Volunteer_services', 'Services'), ('Gifts', 'Gifts')], max_length=50),
        ),
    ]
