# Generated by Django 5.1.3 on 2025-03-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0006_alter_dream_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dream",
            options={"ordering": ["-date_added", "-id"]},
        ),
    ]
