# Generated by Django 5.1.3 on 2025-03-27 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dream", "0008_alter_contribution_dream"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="dream",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contributions",
                to="dream.dream",
            ),
        ),
    ]
